package fr.arthurbrugiere.forgeline.configchecks

import com.google.common.truth.Truth.assertThat
import com.google.common.truth.Truth.assertWithMessage
import org.junit.Test

/**
 * The shipped profiles are generated by the Performance workflow and committed by hand, so they
 * can silently go stale: until 2026-09-27 they only covered the Milestone 0 app shell.
 */
class BaselineProfileTest {
    private val dir = "app/src/release/generated/baselineProfiles"

    @Test
    fun the_baseline_profile_covers_the_daily_journeys() {
        val profile = Repo.text("$dir/baseline-prof.txt")
        for (screen in listOf("inbox/InboxScreen", "feed/FeedScreen", "trending/Trending", "repo/RepoScreen", "search/SearchScreen")) {
            assertWithMessage(screen).that(profile).contains("fr/arthurbrugiere/forgeline/$screen")
        }
    }

    @Test
    fun the_startup_profile_only_holds_launch_code() {
        // It orders the DEX for launch; journey code in it would push launch classes further out.
        val startup = Repo.text("$dir/startup-prof.txt")
        assertThat(startup).contains("fr/arthurbrugiere/forgeline/MainActivity")
        // Hilt registers every ViewModel key at launch, so only screen code is a meaningful probe.
        assertThat(startup).doesNotContain("fr/arthurbrugiere/forgeline/search/SearchScreen")
        assertThat(startup.length).isLessThan(Repo.text("$dir/baseline-prof.txt").length)
    }
}
